### ISSUE TITLE
Bower.io register

### ISSUE THREAD

**Issue by soullivaneuh** [select2/select2-bootstrap-theme#1]
Hi, thanks for this project initiative, looks very nice!

I see the bower.json file but the package is not found on bower.io: http://bower.io/search/?q=select2-bootstrap-theme

Can you please register it? Thanks.

**Comment by tonytonyjan** [comment]
:+1:

**Comment by haydnhkim** [comment]
+1

**Comment by ryanbeymer** [comment]
http://bower.io/docs/creating-packages/#register

**Comment by fk** [comment]
Done!

**Comment by soullivaneuh** [comment]
:+1:
