### ISSUE TITLE
modals?

### ISSUE THREAD

**Issue by morrow95** [select2/select2-bootstrap-theme#12]
What is the story with modals?  In the previous version I had something like this which allowed it to work fine in modals : 

```
.modal-open .select2-drop-mask {
  z-index: 10051;
}

.modal-open .select2-drop {
  z-index: 10052;
}

.modal-open .select2-search {
  z-index: 10053;
}
```

the classes have changed obviously so that will not work or maybe even then it won't.  I haven't looked deeper into it yet, but if anyone has please share.  I did a quick test with the current theme and nothing works in modals... this should be added as a default or at least a commented note in the css with the class names which are affected.

**Comment by morrow95** [comment]
JS Fiddle - https://jsfiddle.net/u5n590cq/6/

I also noticed this works in IE 11, but not in the latest Firefox, Chrome, or Safari.  Anyone else using this is modals and found a solution?

**Comment by fk** [comment]
https://github.com/select2/select2/issues/2152 and https://github.com/select2/select2/issues/600 should help.
