### ISSUE TITLE
downarrow button in wrong place?

### ISSUE THREAD

**Issue by pryankster** [select2/select2-bootstrap-theme#17]
![image](https://cloud.githubusercontent.com/assets/4298409/8259007/2bd110d2-166e-11e5-9727-69cad673cdec.png)

This may or may not be select2-bootstrap-theme's fault -- but I'm at a total loss for how to fix it.  I turned on borders for the arrow button in the debugger, and the box is in the right place (mostly, it seems a little too far to the right), but the actual icon for the arrow button is to the left of the hitbox for the downarrow button)

**Comment by kevin-brown** [comment]
A jsfiddle or place where this can be reproduced would be useful. I can't reproduce this on [the demo page](https://select2.github.io/select2-bootstrap-theme/4.0.0.html)

![image](https://cloud.githubusercontent.com/assets/1991850/8362824/24f3047a-1b49-11e5-9497-2d0ecd323c00.png)

**Comment by pryankster** [comment]
Sorry for the bug report -- I found it, it was some overzealous selector from imported css
