### ISSUE TITLE
optgroup wrong font style

### ISSUE THREAD

**Issue by michele-b** [select2/select2-bootstrap-theme#19]
font-size is wrong, and maybe color also...simply remove it from select2-results__group style

```
.select2-container--bootstrap .select2-results__group {
    /*color: #777;*/
    display: block;
    padding: 6px 12px;
    /*font-size: 12px;*/
    line-height: 1.428571429;
    white-space: nowrap;
}
```

**Comment by NaWer** [comment]
And padding too : 6 4 seems okay.

**Comment by fk** [comment]
Hey @michele-b and @NaWer!

If you take a look at the [Sass](https://github.com/select2/select2-bootstrap-theme/blob/9b033829e02d468576915d79a3ff975c6fea7857/src/select2-bootstrap.scss#L226-L233) (or [Less](https://github.com/select2/select2-bootstrap-theme/blob/9b033829e02d468576915d79a3ff975c6fea7857/src/select2-bootstrap.less#L226-L233)) sources for `.select2-results__group` and compare them to the [style definitions](https://github.com/twbs/bootstrap/blob/7e2741eb1074afc66bdf2fb5c2b65d476cf7f37e/less/dropdowns.less#L152-L160) for Bootstraps "[Dropdown header](http://getbootstrap.com/components/#dropdowns-headers)", you will find that we mimick the latter in terms of `font-size`, `line-height` and `color` (while the padding is based on [Bootstraps definitions for `.form-control`](https://github.com/twbs/bootstrap/blob/7e2741eb1074afc66bdf2fb5c2b65d476cf7f37e/less/forms.less#L118) and we do not alter the browser default styles of the `<strong>` tag the class is applied to).
The Bootstrap documentation describes the purpose of the "Dropdown header" as "to label sections of actions in any dropdown menu" – which is very close to the job that `.select2-results__group` is doing.

If you need to change the styles for `.select2-results__group`, just add some custom CSS, e. g.

``` css
.select2-container--bootstrap .select2-results__group {
    color: inherit;
    font-size: inherit;
    padding: 6px 4px;
}
```

For those who do compile their own select2-bootstrap-theme from the Sass or Less source, the next theme update will introduce a bunch of variables enabling you to change the properties in question.

**Comment by fk** [comment]
As announced, [0.1.0-beta.9](https://github.com/select2/select2-bootstrap-theme/releases/tag/0.1.0-beta.9) provides [dedicated variables](https://github.com/select2/select2-bootstrap-theme/blob/0.1.0-beta.9/src/select2-bootstrap.scss#L275-L282).
