### ISSUE TITLE
Nuget package out of date

### ISSUE THREAD

**Issue by san7hos** [select2/select2-bootstrap-theme#23]
Hi I am not sure if it is in your hands or not but I feel that the nuget package for the theme is utterly outdated: https://www.nuget.org/packages/Select2-Bootstrap/

**Comment by fk** [comment]
Hey there @San7hos!

The nuget package you're reffering to is for the Bootstrap 2 version of https://github.com/t0m/select2-bootstrap-css. This project, select2-bootstrap-theme, is the continuation of the "bootstrap3"-branch (https://github.com/t0m/select2-bootstrap-css/tree/bootstrap3) of said repository. Both versions of select2-bootstrap-css are for Select2 v3 while select2-bootstrap-theme is meant to be used with Select2 v4.

I do not plan to publish this project to nuget, but maybe @kevin-brown wants to chime in.
AFAIK I can not update the nuget package you're reffering to either, please contact the original publisher "myuller" (as listed on https://www.nuget.org/packages/Select2-Bootstrap/).

Closing for now.
