### ISSUE TITLE
.option.load-more results css

### ISSUE THREAD

**Issue by morrow95** [select2/select2-bootstrap-theme#28]
When using ajax and paging there is a 'load more results' message which shows in the dropdown.  There needs to be css added for this to match the rest of the dropdown box.  Something like : 

```
.select2-container--bootstrap .option.load-more {
    padding:6px;
}
```

**Comment by fk** [comment]
Fixed in [0.1.0-beta.9](https://github.com/select2/select2-bootstrap-theme/releases/tag/0.1.0-beta.9).
