### ISSUE TITLE
Problem of heigth with blank <option>

### ISSUE THREAD

**Issue by psohm** [select2/select2-bootstrap-theme#31]
When the option text is blank, the heigth is very reduced

**Comment by psohm** [comment]
please see the blue selection

![sans titre](https://cloud.githubusercontent.com/assets/5886652/12094987/23154f36-b30c-11e5-916e-eba8aa7f5831.png)

**Comment by psohm** [comment]
I made a diry workaround with that function

```
function formatSelect2(option) {
     return option.text != "" ? option.text : $('<div>&nbsp;</div>') ;
}

$(".select2").select2({
    theme: "bootstrap",
    templateResult: formatSelect2
});
```

**Comment by kevin-brown** [comment]
Typically if you are using the blank `<option></option>`, you want to be using the [`placeholder` option](https://select2.github.io/options.html#placeholder). You can see some examples [in the documentation](https://select2.github.io/examples.html#placeholders).
