### ISSUE TITLE
Add on in middle

### ISSUE THREAD

**Issue by jwtoler** [select2/select2-bootstrap-theme#35]
Is it possible to have a input add on in the middle of two select2 drop downs? Or have a select2 drop down - input add on - input text field? Is there a class for this?

Ex: [dropdown][= sign][input field]

**Comment by fk** [comment]
Hi @jtoler! There's no class yet, but a quick [Codepen](http://codepen.io/fk/pen/pEzaOv) draft to help you out.

**Comment by fk** [comment]
Closing this issue as @jtoler never came back and an example to fix this issue has been provided.
