### ISSUE TITLE
Placeholders don't work when loading remote data

### ISSUE THREAD

**Issue by hsleewis** [select2/select2-bootstrap-theme#40]
When I use the bootstrap theme and load the data remotely the placeholders disappear, anyone noticed the same?

**Comment by cyberbit** [comment]
Could it be that you are not returning a blank `<option>` at the top of the remote list? I think that is still necessary, even with side-loaded data.

**Comment by fk** [comment]
@hsleewis @cyberbit As far as I can see, this should work without having to return a blank `<option>`: http://codepen.io/fk/pen/bepgOw

**Comment by fk** [comment]
@hsleewis Any news on this?

**Comment by fk** [comment]
@hsleewis :( ;) – closing for now.
