### ISSUE TITLE
Select2 search input not working in Bootstrap Modal

### ISSUE THREAD

**Issue by Cristiian** [select2/select2-bootstrap-theme#41]
Hello, I noticed that when the select2 is in a modal, the search input is not focusable (search works in IE11 but not in Firefox), also the up and down keys are not working too.
jquery: 1.12.3
bootstrap: 3.3.6
select2: 4.0.2

working page with the issue:
[http://debug.esy.es/select2/](http://debug.esy.es/select2/)

**Comment by cyberbit** [comment]
You can fix this by removing the `tabindex` attribute from the `.modal`. This will allow moving around in the Select2 box, but you lose the ability to close the modal using <kbd>Esc</kbd>.

**Comment by Cristiian** [comment]
Yes it works, would be awesome if we can leave the modal as is.

**Comment by LiamKeene** [comment]
You might prefer to set the `dropdownParent` attribute, which leaves the modal markup intact.

`$("#select2Input").select2({
    dropdownParent: "#modal-container"
  });`

Reference: [Select2 doesn't work when embedded in a bootstrap modal](http://stackoverflow.com/a/33884094)

**Comment by fk** [comment]
Just checked in latest Firefox (v48.0.1 on Mac OS X) and this seems to work fine even without defining `dropdownParent` using Select2 v4.0.3 (as stated in the [update to the StackOverflow answer](http://stackoverflow.com/a/33884094) that @LiamKeene referenced): [Codepen](http://codepen.io/fk/pen/zBgXGZ).

Closing as this is not a select2-bootstrap-theme issue.
Thanks @cyberbit and @LiamKeene for helping out!

**Comment by gocanto** [comment]
this is still not working

**Comment by fk** [comment]
Hi Gustavo! As you can read above, things seem to be working fine.

Please let us know what versions you are using, how you configurated things and ideally provide a JsFiddle, CodePen or the like - only then someone will be able to help.

**Comment by gocanto** [comment]
None of those suggestions worked for me. I just came out with this solution: 

``` css
span.select2-container {
    z-index:10050;
}
```

**Comment by aryeharmon** [comment]
This is not working with solutions give.

**Comment by allandiego** [comment]
Worked for me: firefox 54, select2 4.0.3, bootstrap 3.3.7

https://select2.github.io/options.html#can-i-change-how-the-dropdown-is-placed

$('select').select2({
  dropdownParent: $('#my_amazing_modal')
});

and modal still close with esc key and using tabindex

**Comment by ABDUGO** [comment]
Worked for me on **document ready** for all select2

```javascript
            $('select:not(.normal)').each(function () {
                $(this).select2({
                    dropdownParent: $(this).parent()
                });
            });
```

**Comment by mrmelhay** [comment]
Remove tabindex="-1" from modal. I cheked this solution is worked 100%

**Comment by emielmolenaar** [comment]
Above solution provided by @mrmelhay is working perfectly here! :tada:

**Comment by avidmaulanas** [comment]
If still have problem with css z-index, use this way :smiley: 

Add custom dropdown css class
```javascript
$('select').select2({
   dropdownCssClass: 'custom-dropdown'
});
```

Add css z-index to parent of dropdown when opened 
```javascript
$('select').on('select2:open', function(e){
    $('.custom-dropdown').parent().css('z-index', 99999);
});

**Comment by cyberbit** [comment]
@emielmolenaar I provided the same solution at the top of the thread. ;)

**Comment by emielmolenaar** [comment]
@cyberbit Lol, TL;DR :smile: Thanks!

**Comment by viveroni** [comment]
Put this on your css file

.modal-open .select2-dropdown {
  z-index: 10060;
}

.modal-open .select2-close-mask {
  z-index: 10055;
}

**Comment by AlexanderBV** [comment]
@mrmelhay Thank you.

**Comment by shaktisharma27789** [comment]
Thanku

**Comment by waimyokyaw** [comment]
@gocanto  solution works for me. Thanks!

**Comment by isertic** [comment]
The above suggestions with `.modal .select2-dropdown` caused some visual issues for me when i had a select2 on the same page and then open up the modal with another.

The following worked for me:

`.modal-open .select2-container--open {
  z-index: 999999 !important;
  width:100% !important;
}`

Hope it helps.

**Comment by exzib** [comment]
Neither of the above solutions worked when you have multiple selects on the same page.

**Comment by llper** [comment]
Does not work for me: I can search for items, the dropdown with the results shows up but I can't interact with it

**Comment by armandbechard** [comment]
In my case none of the solutions above work as i want (keeping the ESC key functionality to close the modal), so I tried a really easy different approach that solves the problem: I just remove the tabindex attribute on select2 opening and add it again on select2 close, so i can write on the select2 search input when it is opened and close the modal with ESC when select2 is closed.

**Just like this:**
```javascript
$("#mySelect").select2({
    //here my options
}).on("select2:opening", 
    function(){
        $("#myModal").removeAttr("tabindex", "-1");
}).on("select2:close", 
    function(){ 
        $("#myModal").attr("tabindex", "-1");
    }
});
```

**Comment by abudygold** [comment]
use this code, solved my problem too.

```
$("#select2insidemodal").select2({
    dropdownParent: $("#myModal")
  });
```

[source in stackoverflow](https://stackoverflow.com/questions/18487056/select2-doesnt-work-when-embedded-in-a-bootstrap-modal/33884094#33884094)

**Comment by exzib** [comment]
$(document).ready(function(){
  $('select:not(.normal)').each(function () {
      $(this).select2({
          dropdownParent: $(this).parent().parent()
      });
  });
});

This works fine for me, however it also breaks my select2s that are using APIs to read in and search for options.

**Comment by lzuccaro** [comment]
the following worked for me 

`$.fn.modal.Constructor.prototype.enforceFocus = function() {};
`

**Comment by poloxue** [comment]
@avidmaulanas thank you. Good idea! 

Though the way to modify `enforceFocus` and `tabindex`  both works, I think option `dropdownParent` is better.

**Comment by duzun** [comment]
I have the exact same issue, + what @llper mentioned.
To add to the solutions mentioned here, in my case I was using a data adapter, that was producing options as JS objects. 
I was unable to interact with the results from dropdown because my adapter didn't set the `id` property, only `text` was set, thus the result would show, but no interaction is possible.

**Comment by akgssivagami** [comment]
$('select').select2({
dropdownParent: $('#my_moda_idl')
});


This works fine

**Comment by Eduardomendesc** [comment]
.modal-open .select2-container--open { z-index: 999999 !important; width:100% !important; }

**Comment by Eduardomendesc** [comment]
.modal-open .select2-container--open { z-index: 999999 !important; width:100% !important; } worked for me

**Comment by Eduardomendesc** [comment]
<style type="text/css">
        .modal-open .select2-container--open { z-index: 999999 !important; width:100% !important; }
    </style>


here a correct form

**Comment by numanbintariq** [comment]
Remove tabindex="-1" from the modal.

**Comment by MinionWarrior** [comment]
change the position of the **dropdown** to inherit **select2.full.min.js** and/  **select2.full.min.js**
**select2.full.js**
this
![image](https://user-images.githubusercontent.com/24415364/47894429-bf914300-de9d-11e8-8480-6f6828c75889.png)
to this
![image](https://user-images.githubusercontent.com/24415364/47894457-e18ac580-de9d-11e8-8d03-009231956422.png)

**Comment by lloonnyyaa** [comment]
For Bootstrap modals:
```
function initiateSelect2() {
  $('.select2').select2();
}
initiateSelect2();
// when modal is open
$('.modal').on('shown.bs.modal', function () {
  initiateSelect2();
})
```

**Comment by ikramulmustafa** [comment]
$('#termt').select2({
                    dropdownParent: $("#new-sale")

    });
//termt = Select2 id name
//new-sale = MODAL Id
add this and it fixed my problem

**Comment by lsbescorpion** [comment]
> 
> 
> Put this on your css file
> 
> .modal-open .select2-dropdown {
> z-index: 10060;
> }
> 
> .modal-open .select2-close-mask {
> z-index: 10055;
> }

Perfect for my

**Comment by hiteshchechani** [comment]
This below trick can work for multiple select2 controls on bootbox modal with esc key press escape/close the modal.

// To close your Modal by press Esc key
function ModalEscape() {
    $("#your-modal-container").off("keydown").on("keydown", function (e) {
        if (e.keyCode == 27) {
            $("#your-modal-container").modal('hide');
        }
    });
}

// Register select2 with select type and on close call back MocalEscape
$(".your-select2-control").select2().on("select2:close",
    function () {
        ModalEscape();
    });

**Comment by iamsid** [comment]
Encountered this issue in Chrome v74.0.3 with select2 v4.0.7 when using Bootstrap v4 modal.
Only thing that worked was removing `tab-index` attribute - as suggested by @cyberbit @mrmelhay @MrBuddy18 

I don't read any post explaining the issue. So this is what the issue with my page is: `dropdownParent` is not working correctly. I am able to see the drop down in the correct position in the page, but in the source code, the drop down is created at the end of the page.
Interestingly, if I create select2 from Chrome's console, it works perfectly. But the same code from page-level script tag renders the select input box unusable.

**Comment by ricardoperroni** [comment]
Just insert the dropdownParent

**Comment by poisons77** [comment]
> change the position of the **dropdown** to inherit **select2.full.min.js** and/ **select2.full.min.js**
> **select2.full.js**
> this
> ![image](https://user-images.githubusercontent.com/24415364/47894429-bf914300-de9d-11e8-8480-6f6828c75889.png)
> to this
> ![image](https://user-images.githubusercontent.com/24415364/47894457-e18ac580-de9d-11e8-8d03-009231956422.png)

This fixed my problem. I had both select2 elements in modal window and in normal one. Having all the modals with the class `modal` I changed the code like this:

![image](https://user-images.githubusercontent.com/4058356/85200945-090dfa80-b32e-11ea-8396-a2832e608aab.png)

**Comment by Junior-Shyko** [comment]
> Você pode corrigir isso removendo o `tabindex`atributo do `.modal`. Isso permitirá a movimentação na caixa Select2, mas você perde a capacidade de fechar o modal usando Esc.

Funcionou perfeitamente para mim

**Comment by webdantas** [comment]
Opa, pra mim não funcionou, alguma fonte com o códio todo funcional? Aqui pessoal ajuda, mas não consegui juntar as dicas parciais para compor um unico codigo, alguém já fez rodar o select2 multiple no modal ??

**Comment by adnanaddy** [comment]
To avoid this problem, you may attach the dropdown to the modal itself with the dropdownParent setting:

`$("#select2Input").select2({ dropdownParent: "#modal-container" });`

This will cause the dropdown to be attached to the modal, rather than the <body> element.

Alternatively, you may simply globally override Bootstrap's behavior:

```
// Do this before you initialize any of your modals
$.fn.modal.Constructor.prototype.enforceFocus = function() {};
```

**Comment by mmdm95** [comment]
I liked @ABDUGO solution but make a little fix to work with all bootstrap modals.

```js
('.form-control-select2').each(function () {
    $(this).select2({
        dropdownParent: $(this).closest('.modal'),
    });
});
```

Top scenario is when there is a modal but if you are not sure when it has modal and when it does not, do following checking:

```js
('.form-control-select2').each(function () {
    var obj, parent;
    // you can set your default select2 options in obj
    obj = {
        // default options
    };
    // if there is a modal that select is inside it
    parent = $(this).closest('.modal');
    if (parent.length) {
        obj['dropdownParent'] = parent;
    }
    $(this).select2(obj);
});
```

**Comment by muhammed-salman** [comment]
Can anybody provide solution for select2 3.5 version?

**Comment by ricardoperroni** [comment]
What's your problem?

**Comment by muhammed-salman** [comment]
The same issue but for select2 3.5 v

**Comment by bikmazer** [comment]
Above solution provided by @mrmelhay is working perfectly here! 🎉

**Comment by SherwinVN** [comment]
https://stackoverflow.com/a/19574076/12462555

For bootstrap 3, the solution is:

`$.fn.modal.Constructor.prototype.enforceFocus = function() {};`

Bootstrap 4 renamed the enforceFocus method to _enforceFocus, so you'll need to patch that instead:

`$.fn.modal.Constructor.prototype._enforceFocus = function() {};`

**Comment by emanoellucasml** [comment]
> You might prefer to set the `dropdownParent` attribute, which leaves the modal markup intact.
> 
> `$("#select2Input").select2({ dropdownParent: "#modal-container" });`
> 
> Reference: [Select2 doesn't work when embedded in a bootstrap modal](http://stackoverflow.com/a/33884094)

It worked exactly the way I wanted! Thank you!

**Comment by Naresh-parmar** [comment]
> Worked for me on **document ready** for all select2
> 
> ```js
>             $('select:not(.normal)').each(function () {
>                 $(this).select2({
>                     dropdownParent: $(this).parent()
>                 });
>             });
> ```

**Comment by dantevivero** [comment]
> I liked @ABDUGO solution but make a little fix to work with all bootstrap modals.
> 
> ```js
> ('.form-control-select2').each(function () {
>     $(this).select2({
>         dropdownParent: $(this).closest('.modal'),
>     });
> });
> ```
> 
> Top scenario is when there is a modal but if you are not sure when it has modal and when it does not, do following checking:
> 
> ```js
> ('.form-control-select2').each(function () {
>     var obj, parent;
>     // you can set your default select2 options in obj
>     obj = {
>         // default options
>     };
>     // if there is a modal that select is inside it
>     parent = $(this).closest('.modal');
>     if (parent.length) {
>         obj['dropdownParent'] = parent;
>     }
>     $(this).select2(obj);
> });
> ```

this helped me, thanks a lot!

**Comment by ytpl65** [comment]
> use this code, solved my problem too.
> 
> ```
> $("#select2insidemodal").select2({
>     dropdownParent: $("#myModal")
>   });
> ```
> 
> [source in stackoverflow](https://stackoverflow.com/questions/18487056/select2-doesnt-work-when-embedded-in-a-bootstrap-modal/33884094#33884094)

working for me.

**Comment by MahdiAkrami01** [comment]
use select2 in boostrap modal like this:

```
$('.my-select2').each(function () {
    $(this).select2({
        dropdownParent: $(this).parent(),// fix select2 search input focus bug
    })
})

// fix select2 bootstrap modal scroll bug
$(document).on('select2:close', '.my-select2', function (e) {
    var evt = "scroll.select2"
    $(e.target).parents().off(evt)
    $(window).off(evt)
})
```

**Comment by ennurhekim** [comment]
> You can fix this by removing the `tabindex` attribute from the `.modal`. This will allow moving around in the Select2 box, but you lose the ability to close the modal using Esc.

thanks it works , but esc is working

**Comment by MahdiAkrami01** [comment]
Use [Select2 Bootstrap 5 Theme][1] in **Bootstrap Modal** like this:

 1. fix `select2 & bootstrap` modal **search input** bug.
 2. fix `select2 & bootstrap` modal **scroll bug after select option**.





    jQuery(function() {

      $('.my-select2').each(function() {
        $(this).select2({
          theme: "bootstrap-5",
          dropdownParent: $(this).parent(), // fix select2 search input focus bug
        })
      })

      // fix select2 bootstrap modal scroll bug
      $(document).on('select2:close', '.my-select2', function(e) {
        var evt = "scroll.select2"
        $(e.target).parents().off(evt)
        $(window).off(evt)
      })

    })



    <!DOCTYPE html>
    <html>

    <head>
      
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.2.0/dist/select2-bootstrap-5-theme.min.css" />

      
      <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.0/dist/jquery.slim.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    </head>

    <body>

      
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Launch demo modal
    </button>

      
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Select2 v4.1

              <select class="my-select2">
                <option>Test 1</option>
                <option>Test 2</option>
                <option>Test 3</option>
                <option>Test 4</option>
                <option>Test 5</option>
                <option>Test 6</option>
                <option>Test 7</option>
                <option>Test 8</option>
                <option>Test 9</option>
                <option>Test 10</option>
              </select>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>
    </body>

    </html>




  [1]: https://github.com/apalfrey/select2-bootstrap-5-theme

**Comment by StevenMapes** [comment]
Does anyone have an actual working fix for Bootstrap5? I've tried the removal of the tabindex, using the select2-bootstrap5 CSS but nothing helps. The select list opens behind the modal unless I force a ```.select2-dropdown{z-index:9999}``` but then the search still doesn't work

**Comment by dalimark-nemsu** [comment]
JUST PUT dropdownParent: "#modelID
see sample code below. hope it helps.

$( '#single-select-field' ).select2( {
    theme: "bootstrap-5",
    width: $( this ).data( 'width' ) ? $( this ).data( 'width' ) : $( this ).hasClass( 'w-100' ) ? '100%' : 'style',
    placeholder: $( this ).data( 'placeholder' ),
    dropdownParent: "#modelId",//modelId is from the ID of your modal- SO YOUR TEXTBOX WILL WORK IN MODAL
} );

**Comment by Kanakaraj421** [comment]
Select2 search box is showing in drop-down but cant able able to type like showing read-only this issue only for mozila browser.
I checked all above solutions but no result.
This is search working fine for only 30 input fields using in model in-case i use more than 30 input fields  in bootstrab model search is not working.What is this issue..?.any one please help me...
 i attached working image and not working image
![issue1](https://user-images.githubusercontent.com/111980227/186413181-be758064-6d16-4ae7-bfc7-5baecb072546.png)
![Screenshot from 2022-08-24 17-29-10](https://user-images.githubusercontent.com/111980227/186413208-c19b2370-301d-467a-bacc-75bed60721ae.png)

**Comment by shemshadmh** [comment]
> dropdownParent: "#modelId",//modelId is from the ID of your modal- SO YOUR TEXTBOX WILL WORK IN MODAL

putting form id works for me.
Tnx👍


We can also write this when using jquery:
`dropdownParent: $('#mySelect2').parent()`
