### ISSUE TITLE
Compatibility with input group addon

### ISSUE THREAD

**Issue by mwinandy** [select2/select2-bootstrap-theme#42]
Hello,

The theme is not compatible with input group addon. (border is rounded)
http://getbootstrap.com/components/#input-groups-basic

**Comment by cyberbit** [comment]
Sure it is! It's in the docs: http://select2.github.io/select2-bootstrap-theme/4.0.0.html#input-groups

**Comment by mwinandy** [comment]
Oh ! My bad, i didn't notice it.

Sorry.

**Comment by cocochepeau** [comment]
Hello,

Trying to reopen this one.

There are some issues with the old Opera version (12.18), see down below.

![input group](https://user-images.githubusercontent.com/2019778/27651267-916ee20a-5bec-11e7-93cf-d66d9351b255.png)
