### ISSUE TITLE
Two problems that can be eliminated very easily

### ISSUE THREAD

**Issue by kalidema** [select2/select2-bootstrap-theme#44]
I saw two problems that can be eliminated very easily.
1.  Based on [bower.json specification](https://github.com/bower/spec/blob/master/json.md) please see the highlighted text below:
   **Only one file per filetype.
   Do not include minified files.**
   "main": [
     "dist/select2-bootstrap.css",
     "dist/select2-bootstrap.min.css"
   ],
   So these two rules are ignored in this case, but the best solution would be declaration of scss file as entry-point in order to be consistent with Select2 core. This is very important when you use with nodejs something like main-bower-files or wiredep .
2. Also it is very important to add !default flag to all variables under select2-bootstrap.scss file.

**Comment by fk** [comment]
Yes and yes! Thanks for reporting those @kalidema, ... I keep forgetting both. :/

I will make sure these will land in the next release. Help out with a pull request if you have the time, please - if you are shying away because of the Less version I can take care of that.

**Comment by fk** [comment]
@kalidema Thank you! 👍
