### ISSUE TITLE
Don't set font-family

### ISSUE THREAD

**Issue by amastaneh** [select2/select2-bootstrap-theme#50]
I think it's not recommended and it's not required that change font-family of select item because
- `select2.css` has not change any font-family
- Make conflict with default font of project
- Consume time and bandwidth a little

**Comment by kevin-brown** [comment]
The font-family which appears to be used is the same as the default `$font-family` value set by Bootstrap, which you should be able to override in the LESS or SASS files.

> Consume time and bandwidth a little

Time? Sure, changing the line where it sets the font-family.
Bandwidth?

**Comment by fk** [comment]
@kevin-brown I might not see the forest for the trees right now, but I think @amastaneh is right – select2-bootstrap-theme should just inherit `font-family` instead of defining its own, just like the Select2 default themes do (most probably for the exact same reasons mentioned).

**Comment by kevin-brown** [comment]
You're right, one thing I forgot about this is that most people using Bootstrap are using the compiled files and not the source files - so the Bootstrap variable we use for the font family is never actually being changed. Considering that, it makes sense to not override the font family on our side.

**Comment by fk** [comment]
@kevin-brown 👍 - will be taken care of in the next release.

**Comment by fk** [comment]
Fixed in [0.1.0-beta.9](https://github.com/select2/select2-bootstrap-theme/releases/tag/0.1.0-beta.9).
