### ISSUE TITLE
Missing dependencies in 'bower.json'?

### ISSUE THREAD

**Issue by nelson6e65** [select2/select2-bootstrap-theme#52]
`bower.json` chouldn't have `select2` as dependency? 

This will ensure using the right theme version compatible with `select2` version used in own projects.

The same applies to `bootstrap`.

**Comment by fk** [comment]
@nelson6e65 I gave it a shot in [0.1.0-beta.9](https://github.com/select2/select2-bootstrap-theme/releases/tag/0.1.0-beta.9) – could you please check?
