### ISSUE TITLE
Multiple input-sm height problem

### ISSUE THREAD

**Issue by policchio** [select2/select2-bootstrap-theme#56]
Hi,
thank you for the great job.

I have a problem with the class "input-sm" combined with multiple choices: i can't obtain the right height.
You can see the problem here: https://codepen.io/policchio/pen/dOPLdp
If I try to delete "height: auto" in the class ".select2-selection--multiple" I obtain the right height, but obviously the wrong behaviour.

Thank you in advance!

**Comment by fk** [comment]
Hi @policchio!

Always include `select2-bootstrap.css` *after* `select2.css`, then your issue will go away.
Fixed CodePen here: https://codepen.io/fk/pen/MpzwKp
