### ISSUE TITLE
Input-lg doesn't work

### ISSUE THREAD

**Issue by jrean** [select2/select2-bootstrap-theme#58]
Hi,

- `jquery@3.1.1`
- `bootstrap-sass@3.3.7`
- `select2@4.0.3`
- `select2-bootstrap-theme@0.1.0-beta.9`

- I required the packages with `yarn`
- I load the select2 + select2-bootstrap css files
- I load the select2 js file
- I declare to use the bootstrap theme globaly

Nothing to do, my input is not "LG", nor "SM"...
When I load the page, my default select is displayed in LG then a few milliseconds later the plugins loads I guess and the input change its height to "Medium".

```
<select class="companies-select2 form-control input-lg select2-hidden-accessible" name="company_id" tabindex="-1" aria-hidden="true"><option value="1">Google</option><option value="2">Yahoo</option></select>
```

Am I missing something?

**Comment by staff0rd** [comment]
I have this and also don't see the result rendered large;
~~~html
<form class="form-horizontal">
    <div class="form-group form-group-lg">
        <label class="col-sm-2 control-label" for="mySelect">MyLabel</label>
        <div class="col-sm-10">
            <select class="form-control" id="mySelect"></select>
        </div>
    </div>
</form>
~~~

Somehow it's working on the [demo](https://select2.github.io/select2-bootstrap-theme/4.0.3.html#horizontal-form-group-sizes) tho.

EDIT;
NVM, I wasn't setting the theme;

~~~javascript
$.fn.select2.defaults.set( "theme", "bootstrap" );
~~~

**Comment by sigo** [comment]
This issue should be closed now I think. Adding `.form-group-lg` class at `.form-group` element and applying theme works great.

**Comment by jrean** [comment]
@sigo thank you. You are right!

For reference: `<div class="form-group form-group-lg">`
