### ISSUE TITLE
jsdelivr support?

### ISSUE THREAD

**Issue by leowinterde** [select2/select2-bootstrap-theme#59]
Hi,
are there any plans to offer this file over [jsdelivr.com](http://www.jsdelivr.com/)?

https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

I would be glad.

**Comment by fk** [comment]
Hi @LeoWinterDE! I hope to do this later tonight.

**Comment by fk** [comment]
@LeoWinterDE Just submitted a pull request, fingers crossed that I did the right thing … ;)

**Comment by leowinterde** [comment]
Looks good 👍

**Comment by fk** [comment]
@LeoWinterDE It's available now: http://www.jsdelivr.com/?query=select2-bootstrap-theme 🙌
