### ISSUE TITLE
.select2-bootstrap-prepend

### ISSUE THREAD

**Issue by ghost** [select2/select2-bootstrap-theme#6]
![screen shot 2015-04-15 at 09 59 29](https://cloud.githubusercontent.com/assets/6951966/7155762/231b2646-e359-11e4-810f-c57d2a4e72ef.png)

![screen shot 2015-04-15 at 10 22 53](https://cloud.githubusercontent.com/assets/6951966/7155797/67e92a84-e359-11e4-8899-0dd6370fc1fc.png)

I've eliminated all CSS/JS files on a one-by-one basis to check that there are no conflicts. However, it seems that I can't get select2-bootstrap-prepend to display the field correctly.

I'm using Bootstrap v3.3.4 and Select2 4.0.0-rc.2.

```
<div class="input-group select2-bootstrap-prepend">
<span class="input-group-addon"><i class="fa fa-fw fa-globe"></i></i></span>
<select id="join_country" name="join_country" class="form-control" value="" required="required">
<option></option>
<option>01</option>
<option>02</option>
</select>
</div>
<script>
$("#join_country").select2({
minimumResultsForSearch: -1,
placeholder: "Country",
allowClear: true
});
</script>
```

**Comment by fk** [comment]
Hi @wnjken – just tell Select2 [to use the theme](https://select2.github.io/examples.html#themes) by adding `theme: "bootstrap"` when initializing:

```
$("#join_country").select2({
    minimumResultsForSearch: -1,
    placeholder: "Country",
    allowClear: true,
    theme: "bootstrap"
});
```

Here's a quick [CodePen demo](http://codepen.io/fk/pen/myNjWe).
