### ISSUE TITLE
Focus is lost for most scenarios when the dropdown list closes

### ISSUE THREAD

**Issue by Vaccano** [select2/select2-bootstrap-theme#61]
NOTE: This is a Chome and Firefox only bug. (IE 11 works fine)

Focus is lost when you do one of the following:

- Select an item from the list (Using the filter, arrow keys or mouse)
- Drop down the pick list then press tab (without selecting anything)

Basically when the dropdown list closes, focus is lost.  Pressing tab moves the focus to the first item on the page.

Repro Steps:

1. Load this URL: https://select2.github.io/examples.html
2. Click on the second drop down on the page (or any that has Select2 applied)
3. Select an option
4. Press Tab
RESULT:  The Logo at the top of the screen is focused.

Tested on Chrome 56 and Firefox 38.5.1 using Windows 7 also tested with Chrome in my app using the latest build as of 3/10/2017.

UPDATE: This bug does not occur if you use the "minimumResultsForSearch: Infinity" option.  But then you cannot type to match on items in the list.

**Comment by fk** [comment]
Hi @Vaccano!

This looks like an issue with Select2 itself, not with select2-bootstrap-theme. Please open an issue on the [Select2 issue tracker](https://github.com/select2/select2/issues) after checking if your issue has not already been reported. Thank you!
