### ISSUE TITLE
select2 input-group border radius

### ISSUE THREAD

**Issue by drvid** [select2/select2-bootstrap-theme#62]
![select2-input-group](https://cloud.githubusercontent.com/assets/641266/23921061/95f38b62-08d3-11e7-945c-c11db05706a0.png)

As seen in the screenshot, border radius on the select2 element is not adjusted when situated inside an input group.

Reference:
http://getbootstrap.com/components/#input-groups

**Comment by fk** [comment]
Hi @drvid!

For now you need to add `.select2-bootstrap-prepend` or `.select2-bootstrap-append` to the `.input-group` wrapper element to address Select2's corresponding border-radii. Also see the [documentation](https://select2.github.io/select2-bootstrap-theme/4.0.3.html#input-groups) or [this CodePen](http://codepen.io/fk/pen/gmBNNe).

This will be obsolete once https://github.com/select2/select2-bootstrap-theme/pull/54 gets merged.

**Comment by fk** [comment]
#54 is included in the new release 0.1.0-beta.10 and the helper classes mentioned above are not necessary anymore. Just upgrading to the new version should resolve your problem.
