### ISSUE TITLE
select2 opens on disabled

### ISSUE THREAD

**Issue by brunomiguelpinto** [select2/select2-bootstrap-theme#67]
When its disabled, the select2 opens on enter and on space. Can someone help?

**Comment by bmccombs01** [comment]
You can add a callback that prevents the dropdown from opening on the `select2:opening` event. Like:
```
var $select = $("select");
$select.on("select2:opening", function (event) {
  if ($select.is(":disabled")) {
    event.preventDefault();
  }
});
``` 

It has been working wonderfully for me.
