### ISSUE TITLE
No LESS love?

### ISSUE THREAD

**Issue by mrchief** [select2/select2-bootstrap-theme#7]
The less file is empty. Personally I like SASS more but sites like [these](http://bootstrap-live-customizer.com/) accept .less only. And I need them cause my bootstrap variables are customized and are in less only. :(

**Comment by joonas-lahtinen** [comment]
This would also help bower users. +1

**Comment by mrchief** [comment]
:+1:

**Comment by joonas-lahtinen** [comment]
Great, thanks!
